name: 'Git pr release action'
description: 'Create a release pull-request.'
author: 'grassedge'
inputs:
  owner:
    description: "Default is current repository's owner."
  repo:
    description: "Default is current repository's name."
  base:
    description: "Base branch of the release pull-request."
    required: true
  head:
    description: "Head branch of the release pull-request. Typically, it is the same as a subscribed branch."
    required: true
  assign:
    description: "If true, assign each pull-req's assignees to the release pull-req"
  requestReviewers:
    description: "If true, assign each pull-req's reviewers to the release pull-req"
  labels:
    description: 'Labels that is added to the release pull-request'
  template:
    description: 'Path to the template you want to use.'
  tz:
    description: 'Used to generate the version string.'
  token:
    description: 'Used to create a pull request.'
    required: true
runs:
  using: 'node20'
  main: 'lib/index.js'
branding:
  icon: 'check-square'
  color: 'gray-dark'
